-- drop table if exists public.items;

CREATE TABLE IF NOT EXISTS public.items (
                                     id VARCHAR  NOT NULL,
                                     date TIMESTAMP  NOT NULL,
                                     parent_id VARCHAR,
                                     url VARCHAR(255),
                                     type VARCHAR(255) NOT NULL,
                                     size INT8,
                                     CONSTRAINT pk_item PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS public.history (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                            item_id VARCHAR  NOT NULL,
                                            date TIMESTAMP  NOT NULL,
                                            parent_id VARCHAR,
                                            url VARCHAR(255),
                                            type VARCHAR(255) NOT NULL,
                                            size INT8,
                                            CONSTRAINT pk_history PRIMARY KEY (id)

);

